# Bienvenidos a Trailerflix
GET http://localhost:3000/

### ACTOR
# Crear un nuevo actor
POST http://localhost:3000/actor/agregar-actor
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Perez"
}

# Obtener un actor por ID
GET http://localhost:3000/actor/1

# Crear múltiples actores ANDA
POST http://localhost:3000/actor/agregar-actores
Content-Type: application/json

[
    { "nombre": "Ana", "apellido": "Gomez" },
    { "nombre": "Luis", "apellido": "Lopez" }
]

# Listar todos los actores ANDA
GET http://localhost:3000/actor/listar-actores

# Actualizar un actor por ID
PUT http://localhost:3000/actor/modificar-actor/1
Content-Type: application/json

{
    "nombre": "Carlos",
    "apellido": "Garcia"
}

# Borrar un actor por ID
DELETE http://localhost:3000/actor/borrar-actor/1

---

### CATEGORÍA
# Crear una nueva categoría
POST http://localhost:3000/agregar-categoria
Content-Type: application/json

{
    "categoria": "pelicula-2"
}

# Obtener una categoría por ID
GET http://localhost:3000/categoria/1

# Listar todas las categorías
GET http://localhost:3000/listar-categorias

# Actualizar una categoría por ID
PUT http://localhost:3000/modificar-categoria/1
Content-Type: application/json

{
    "nombre": "Drama"
}

# Borrar una categoría por ID
DELETE http://localhost:3000/borrar-categoria/1

---

### GEN
# Crear un nuevo gen
POST http://localhost:3000/agregar-gen
Content-Type: application/json

{
    "nombre": "Gen A"
}

# Obtener un gen por ID
GET http://localhost:3000/gen/1

# Listar todos los gen
GET http://localhost:3000/listar-gen

# Actualizar un gen por ID
PUT http://localhost:3000/modificar-gen/1
Content-Type: application/json

{
    "nombre": "Gen B"
}

# Borrar un gen por ID
DELETE http://localhost:3000/borrar-gen/1

---

### CONTENIDO
# Crear un nuevo contenido
POST http://localhost:3000/contenido/agregar-contenido
Content-Type: application/json

{
    "titulo": "Película X",
    "resumen": "Descripción de la película",
    "busqueda": "Pirulitp se encontro un claivto",
    "trailer": "https://www.youtube.com/watch?v=e2E1aBQ5yA0",
    "categoria_id": "2",
    "duracion": "160",
    "gen": "3"
}

# Obtener un contenido por ID
GET http://localhost:3000/contenido/1

# Listar todos los contenidos
GET http://localhost:3000/listar-contenidos

# Actualizar un contenido por ID
PUT http://localhost:3000/modificar-contenido/1
Content-Type: application/json

{
    "titulo": "Película Y",
    "descripcion": "Descripción actualizada"
}

# Borrar un contenido por ID
DELETE http://localhost:3000/borrar-contenido/1

---

### GÉNERO
# Crear un nuevo género
POST http://localhost:3000/agregar-genero
Content-Type: application/json

{
    "nombre": "Acción"
}

# Obtener un género por ID
GET http://localhost:3000/genero/1

# Listar todos los géneros
GET http://localhost:3000/listar-generos

# Actualizar un género por ID
PUT http://localhost:3000/modificar-genero/1
Content-Type: application/json

{
    "nombre": "Aventura"
}

# Borrar un género por ID
DELETE http://localhost:3000/borrar-genero/1


# Traer todas las pelis y sus actores 
GET http://localhost:3000/contenidos/actor

###



### Pedidos para categorias

#Traer todas las categorias

# Crear una categoria
POST http://localhost:3000/categoria
Content-Type: application/json

{
  "categoria": "pelicula"
}

#Modificar una categoria

#Borrar una categoria



