# Bienvenidos a Trailerflix HACER
GET http://localhost:3000/

### ACTOR
# Crear un nuevo actor ANDA
POST http://localhost:3000/actor/agregar-actor
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Perez"
}

# Obtener un actor por ID ANDA
GET http://localhost:3000/actor/1

# Crear múltiples actores ANDA
POST http://localhost:3000/actor/agregar-actores
Content-Type: application/json

[
    { "nombre": "Ana", "apellido": "Gomez" },
    { "nombre": "Luis", "apellido": "Lopez" }
]

# Listar todos los actores ANDA
GET http://localhost:3000/actor/listar-actores

# Actualizar un actor por ID ANDA
PUT http://localhost:3000/actor/modificar-actor/1
Content-Type: application/json

{
    "nombre": "Carlos",
    "apellido": "Garcia"
}

# Borrar un actor por ID ANDA
DELETE http://localhost:3000/actor/borrar-actor/1

---

### CATEGORÍA
# Crear una nueva categoría ANDA
POST http://localhost:3000/categoria/agregar-categoria
Content-Type: application/json

{
    "categoria": "cortometrajes"
}

# Obtener una categoría por ID ANDA
GET http://localhost:3000/categoria/categoria/1

# Listar todas las categorías ANDA
GET http://localhost:3000/categoria/listar-categorias

# Actualizar una categoría por ID ANDA
PUT http://localhost:3000/categoria/modificar-categoria/2
Content-Type: application/json

{
    "categoria": "peliculones"
}

# Borrar una categoría por ID ANDA
DELETE http://localhost:3000/categoria/borrar-categoria/1

---

### GEN
# Crear un nuevo gen ANDA
POST http://localhost:3000/gen/agregar-gen
Content-Type: application/json

{
    "gen": "Accion"
}

# Obtener un gen por ID ANDA
GET http://localhost:3000/gen/gen/1

# Listar todos los gen ANDA
GET http://localhost:3000/gen/listar-gen

# Actualizar un gen por ID ANDA
PUT http://localhost:3000/gen/modificar-gen/3
Content-Type: application/json

{
    "gen": "ciencia ficcion actualizada"
}

# Borrar un gen por ID ANDA
DELETE http://localhost:3000/gen/borrar-gen/1

---

### CONTENIDO
# Crear un nuevo contenido ANDA
POST http://localhost:3000/contenido/agregar-contenido
Content-Type: application/json

{
    "titulo": "Película X",
    "resumen": "Descripción de la película",
    "busqueda": "Pirulitp se encontro un claivto",
    "trailer": "https://www.youtube.com/watch?v=e2E1aBQ5yA0",
    "categoria_id": "2",
    "duracion": "160",
    "gen_id": "3"
}

# Crear muchos contenidos 
POST http://localhost:3000/contenido/agregar-contenidos
[
    {
        "titulo": "The Mandalorian",
        "resumen": "Ambientada tras la caída del Imperio y antes de la aparición de la Primera Orden, la Serie sigue los pasos de un pistolero solitario en las aventuras que protagoniza en los confines de la galaxia, donde no alcanza la autoridad de la Nueva República.",
        "busqueda": "The Mandalorian, Sci-Fi, Fantasía, Suspenso, Pedro Pascal, Carl Weathers, Misty Rosas, Chris Bartlett, Rio Hackford, Giancarlo Esposito",
        "trailer": "https://www.youtube.com/embed/aOC8E8z_ifw",
        "categoria_id": "1",
        "temporadas": "2",
        "duracion": "N/A",
        "gen_id": "3"
    },
    {
        "titulo": "The Umbrella Academy",
        "resumen": "La muerte de su padre reúne a unos hermanos distanciados y con extraordinarios poderes que descubren impactantes secretos y una amenaza que se cierne sobre la humanidad.",
        "busqueda": "The Umbrella Academy, Sci-Fi, Fantasía, Drama, Tom Hopper, David Castañeda, Emmy Raver-Lampman, Robert Sheehan, Aidan Gallagher, Elliot Page",
        "trailer": "https://www.youtube.com/embed/KHucKOK-Vik",
        "categoria_id": "1",
        "temporadas": "1",
        "duracion": "N/A",
        "gen_id": "4"
    },
    {
        "titulo": "Gambito de Dama",
        "resumen": "En los cincuenta, una joven de un orfanato descubre que tiene un increíble don para el ajedrez y recorre el arduo camino a la fama mientras lucha contra las adicciones.",
        "busqueda": "Gambito de Dama, Drama, Ficción, Sucesos, Anya Taylor-Joy, Thomas Brodie-Sangster, Harry Melling, Moses Ingram, Chloe Pirrie, Janina Elkin",
        "trailer": "https://www.youtube.com/embed/lbleRbyGKL4",
        "categoria_id": "1",
        "temporadas": "1",
        "duracion": "N/A",
        "gen_id": "4"
    },
    {
        "titulo": "Riverdale",
        "resumen": "El paso a la edad adulta incluye sexo, romance, escuela y familia. Para Archie y sus amigos, también hay misterios oscuros.",
        "busqueda": "Riverdale, Drama, Misterio, Ficción, Lili Reinhart, Casey Cott, Camila Mendes, Marisol Nichols, Madelaine Petsch, Mädchen Amick",
        "trailer": "https://www.youtube.com/embed/HxtLlByaYTc",
        "categoria_id": "1",
        "temporadas": "5",
        "duracion": "N/A",
        "gen_id": "4"
    },
    {
        "titulo": "The Crown",
        "resumen": "Este drama narra las rivalidades políticas y el romance de la reina Isabel II, así como los sucesos que moldearon la segunda mitad del siglo XX.",
        "busqueda": "The Crown, Drama, Suceso Real, Claire Fox, Olivia Colman, Matt Smith, Tobias Menzies, Vanesa Kirby, Helena Bonham Carter",
        "trailer": "https://www.youtube.com/embed/JWtnJjn6ng0",
        "categoria_id": "1",
        "temporadas": "4",
        "duracion": "N/A",
        "gen_id": "6"
    },
    {
        "titulo": "Enola Holmes",
        "resumen": "La hermana menor de Sherlock, descubre que su madre ha desaparecido y se dispone a encontrarla.",
        "busqueda": "Enola Holmes, Ficción, Drama, Misterio, Millie Bobby Brown, Henry Cavill, Sam Claflin, Helena Bonham Carter, Louis Partridge, Adeel Akhtar",
        "trailer": "https://www.youtube.com/embed/3t1g2pa355k",
        "categoria_id": "2",
        "temporadas": "N/A",
        "duracion": "97",
        "gen_id": "4"
    },
    {
        "titulo": "Guasón",
        "resumen": "Arthur Fleck es un hombre ignorado por la sociedad, cuya motivación en la vida es hacer reír. Pero una serie de trágicos acontecimientos le llevarán a ver el mundo de otra forma.",
        "busqueda": "Guasón, The Joker, Crimen, Suspenso, Drama, DC Comics, Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy, Brett Cullen, Shea Whigham",
        "trailer": "https://www.youtube.com/embed/zAGVQLHvwOY",
        "categoria_id": "2",
        "temporadas": "N/A",
        "duracion": "97",
        "gen_id": "7"
    },
    {
        "titulo": "Avengers: End Game",
        "resumen": "Después de los devastadores eventos de los Vengadores: Infinity War, el universo está en ruinas. Los Vengadores se reúnen una vez más para revertir las acciones de Thanos.",
        "busqueda": "Vengadores, Los vengadores, Marvel, The Avengers: End Game, Aventura, Sci-Fi, Acción, Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner",
        "trailer": "https://www.youtube.com/embed/TcMBFSGVi1c",
        "categoria_id": "2",
        "temporadas": "N/A",
        "duracion": "97",
        "gen_id": "3"
    },
    {
        "titulo": "Juego de tronos",
        "resumen": "En un mundo fantástico y en un contexto medieval, varias familias se disputan el poder para dominar el territorio ficticio de Poniente y tomar el control de los Siete Reinos.",
        "busqueda": "Juego de tronos, Game of Thrones, Aventura, Fantasía, Drama, Emilia Clarke, Lena Headey, Sophie Turner, Kit Harington, Peter Dinklage, Nikolaj Coster-Waldau",
        "trailer": "https://www.youtube.com/embed/KPLWWIOCOOQ",
        "categoria_id": "1",
        "temporadas": "8",
        "duracion": "N/A",
        "gen_id": "5"
    },
    {
        "titulo": "The Flash",
        "resumen": "Sigue las veloces aventuras de Barry Allen, un joven con el deseo de ayudar a los demás que se encuentra cargado de un increíble poder para moverse a increíbles velocidades.",
        "busqueda": "The Flash, DC Comics, Sci-Fi, Fantasía, Acción, Grant Gustin, Carlos Valdes, Danielle Panabaker, Candice Patton, Jesse L. Martin, Tom Cavanagh",
        "trailer": "https://www.youtube.com/embed/Yj0l7iGKh8g",
        "categoria_id": "1",
        "temporadas": "6",
        "duracion": "N/A",
        "gen_id": "3"
    },
    {
        "titulo": "The Big Bang Theory",
        "resumen": "Leonard y Sheldon son dos físicos que comparten trabajo y apartamento, enfrentándose a situaciones cómicas con su nueva vecina Penny.",
        "busqueda": "The Big Bang Theory, La teoría del Big Bang, Comedia, Fantasía, Ficción, Jim Parsons, Johnny Galecki, Kaley Cuoco, Simon Helberg, Kunal Nayyar, Melissa Rauch, Mayim Bialik",
        "trailer": "https://www.youtube.com/embed/WBb3fojgW0Q",
        "categoria_id": "1",
        "temporadas": "12",
        "duracion": "N/A",
        "gen_id": "9"
    },
    {
        "titulo": "Friends",
        "resumen": "'Friends' narra las aventuras y desventuras de seis jóvenes de Nueva York que forman una unida pandilla de amigos que viven en Manhattan.",
        "busqueda": "Friends, Amigos, Comedia, Familia, Drama, Sitcom, Jennifer Aniston, Courteney Cox, Lisa Kudrow, David Schwimmer, Matthew Perry, Matt LeBlanc",
        "trailer": "https://www.youtube.com/embed/ekYGfU0XIx0",
        "categoria_id": "1",
        "temporadas": "10",
        "duracion": "N/A",
        "gen_id": "9"
    },
    {
        "titulo": "Anne with an 'E'",
        "resumen": "Anne Shirley es una niña huérfana que vive en un pequeño pueblo y transforma su vida gracias a su fuerte personalidad, intelecto e imaginación.",
        "busqueda": "Anne with an 'E', Drama, Familia, Western, Amybeth McNulty, Geraldine James, R. H. Thomson, Corrine Koslo, Dalila Bela, Lucas Jade Zumann",
        "trailer": "https://www.youtube.com/embed/M4T-_aB8smU",
        "categoria_id": "1",
        "temporadas": "3",
        "duracion": "N/A",
        "gen_id": "4"
    },
    {
        "titulo": "The Good Place",
        "resumen": "Tras su muerte, Eleanor Shellstrop descubre que está en el 'Buen Lugar', un paraíso que resulta no ser tan perfecto como ella creía.",
        "busqueda": "The Good Place, Comedia, Fantasía, Ficción, Kristen Bell, Ted Danson, William Jackson Harper, Jameela Jamil, D'Arcy Carden, Manny Jacinto",
        "trailer": "https://www.youtube.com/embed/bYzgr1u2x8I",
        "categoria_id": "1",
        "temporadas": "4",
        "duracion": "N/A",
        "gen_id": "9"
    },
    {
        "titulo": "Breaking Bad",
        "resumen": "Walter White es un profesor de química que se convierte en un fabricante de metanfetaminas tras ser diagnosticado con cáncer.",
        "busqueda": "Breaking Bad, Drama, Crimen, Acción, Bryan Cranston, Aaron Paul, Anna Gunn, Dean Norris, Betsy Brandt, RJ Mitte",
        "trailer": "https://www.youtube.com/embed/HhesaQXLuRY",
        "categoria_id": "1",
        "temporadas": "5",
        "duracion": "N/A",
        "gen_id": "4"
    }
]



# Obtener un contenido por ID ANDA
GET http://localhost:3000/contenido/contenido/1

# Listar todos los contenidos ANDA
GET http://localhost:3000/contenido/listar-contenidos

# Modificar un contenido por ID ANDA
PUT http://localhost:3000/contenido/modificar-contenido/1
Content-Type: application/json

{
    "titulo": "Película XXXX",
    "resumen": "La peli no es porno",
    "busqueda": "Pirulitp se encontro un claivto",
    "trailer": "https://www.youtube.com/watch?v=e2E1aBQ5yA0",
    "categoria_id": "2",
    "duracion": "160",
    "gen_id": "3"
}

# Borrar un contenido por ID ANDA
DELETE http://localhost:3000/contenido/borrar-contenido/5

---

### GÉNERO
# Crear un nuevo género ANDA
POST http://localhost:3000/genero/agregar-genero
Content-Type: application/json

{
    "genero": "Acción"
}

# Obtener un género por ID ANDA
GET http://localhost:3000/genero/genero/1

# Listar todos los géneros ANDA
GET http://localhost:3000/genero/listar-generos

# Modificar un género por ID ANDA
PUT http://localhost:3000/genero/modificar-genero/13
Content-Type: application/json

{
    "genero": "western-occidental"
}

# Borrar un género por ID ANDA
DELETE http://localhost:3000/genero/borrar-genero/1

### POSTER

# Listar todos los posters
GET http://localhost:3000/poster/listar-poster
Accept: application/json

# Obtener un poster por ID
GET http://localhost:3000/poster/poster/1
Accept: application/json

# Agregar un nuevo poster
POST http://localhost:3000/poster/agregar-poster
Content-Type: application/json

{
    "image": "./posters/3.jpg",
    "contenido_id": "Descripción del nuevo poster",
    "fecha": "2024-10-27",
    "imagenUrl": "http://example.com/imagen.jpg"
}

# Modificar un poster existente
PUT http://localhost:3000/poster/modificar-poster/1
Content-Type: application/json

{
    "titulo": "Poster Modificado",
    "descripcion": "Descripción del poster modificado",
    "fecha": "2024-10-28",
    "imagenUrl": "http://example.com/imagen-modificada.jpg"
}

# Borrar un poster por ID
DELETE http://localhost:3000/poster/borrar-poster/1
Accept: application/json

###



# Traer todas las pelis y sus actores 
GET http://localhost:3000/contenidos/actor

###



### Pedidos para categorias

#Traer todas las categorias

# Crear una categoria
POST http://localhost:3000/categoria
Content-Type: application/json

{
  "categoria": "pelicula"
}

#Modificar una categoria

#Borrar una categoria



