
### ACTOR
# Crear un nuevo actor ANDA
POST http://localhost:3000/actor/agregar-actor
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Perez"
}

# Obtener un actor por ID ANDA
GET http://localhost:3000/actor/1

# Crear múltiples actores ANDA
POST http://localhost:3000/actor/agregar-actores
Content-Type: application/json

[
    { "nombre": "Ana", "apellido": "Gomez" },
    { "nombre": "Luis", "apellido": "Lopez" }
]

# Listar todos los actores ANDA
GET http://localhost:3000/actor/listar-actores

# Actualizar un actor por ID ANDA
PUT http://localhost:3000/actor/modificar-actor/1
Content-Type: application/json

{
    "nombre": "Carlos",
    "apellido": "Garcia"
}

# Borrar un actor por ID ANDA
DELETE http://localhost:3000/actor/borrar-actor/1

---

### CATEGORÍA
# Crear una nueva categoría ANDA
POST http://localhost:3000/categoria/agregar-categoria
Content-Type: application/json

{
    "categoria": "cortometrajes"
}

# Obtener una categoría por ID ANDA
GET http://localhost:3000/categoria/categoria/1

# Listar todas las categorías ANDA
GET http://localhost:3000/categoria/listar-categorias

# Actualizar una categoría por ID ANDA
PUT http://localhost:3000/categoria/modificar-categoria/2
Content-Type: application/json

{
    "categoria": "peliculones"
}

# Borrar una categoría por ID ANDA
DELETE http://localhost:3000/categoria/borrar-categoria/1

---

### GEN
# Crear un nuevo gen ANDA
POST http://localhost:3000/gen/agregar-gen
Content-Type: application/json

{
    "gen": "Accion"
}

# Obtener un gen por ID ANDA
GET http://localhost:3000/gen/gen/1

# Listar todos los gen ANDA
GET http://localhost:3000/gen/listar-gen

# Actualizar un gen por ID ANDA
PUT http://localhost:3000/gen/modificar-gen/3
Content-Type: application/json

{
    "gen": "ciencia ficcion actualizada"
}

# Borrar un gen por ID ANDA
DELETE http://localhost:3000/gen/borrar-gen/1

---

### CONTENIDO
# Crear un nuevo contenido ANDA
POST http://localhost:3000/contenido/agregar-contenido
Content-Type: application/json

{
    "titulo": "Película X",
    "resumen": "Descripción de la película",
    "busqueda": "Pirulitp se encontro un claivto",
    "trailer": "https://www.youtube.com/watch?v=e2E1aBQ5yA0",
    "categoria_id": "2",
    "duracion": "160",
    "gen_id": "3"
}

# Crear muchos contenidos ANDA
POST http://localhost:3000/contenido/agregar-contenidos
[
        {
        "titulo": "The Umbrella Academy",
        "resumen": "La muerte de su padre reúne a unos hermanos distanciados y con extraordinarios poderes que descubren impactantes secretos y una amenaza que se cierne sobre la humanidad.",
        "busqueda": "The Umbrella Academy, Sci-Fi, Fantasía, Drama, Tom Hopper, David Castañeda, Emmy Raver-Lampman, Robert Sheehan, Aidan Gallagher, Elliot Page",
        "trailer": "https://www.youtube.com/embed/KHucKOK-Vik",
        "categoria_id": 1,
        "temporadas": 1,
        "duracion": null,
        "gen_id": 4
    },
    {
        "titulo": "Gambito de Dama",
        "resumen": "En los cincuenta, una joven de un orfanato descubre que tiene un increíble don para el ajedrez y recorre el arduo camino a la fama mientras lucha contra las adicciones.",
        "busqueda": "Gambito de Dama, Drama, Ficción, Sucesos, Anya Taylor-Joy, Thomas Brodie-Sangster, Harry Melling, Moses Ingram, Chloe Pirrie, Janina Elkin",
        "trailer": "https://www.youtube.com/embed/lbleRbyGKL4",
        "categoria_id": 1,
        "temporadas": 1,
        "duracion": null,
        "gen_id": 4
    }
]


# Obtener un contenido por ID ANDA
GET http://localhost:3000/contenido/contenido/1

# Listar todos los contenidos ANDA
GET http://localhost:3000/contenido/listar-contenidos

# Modificar un contenido por ID ANDA
PUT http://localhost:3000/contenido/modificar-contenido/1
Content-Type: application/json

{
    "titulo": "Película XXXX",
    "resumen": "La peli no es porno",
    "busqueda": "Pirulitp se encontro un claivto",
    "trailer": "https://www.youtube.com/watch?v=e2E1aBQ5yA0",
    "categoria_id": "2",
    "duracion": "160",
    "gen_id": "3"
}

# Borrar un contenido por ID ANDA
DELETE http://localhost:3000/contenido/borrar-contenido/5

---

### GÉNERO
# Crear un nuevo género ANDA
POST http://localhost:3000/genero/agregar-genero
Content-Type: application/json

{
    "genero": "Acción"
}

# Obtener un género por ID ANDA
GET http://localhost:3000/genero/genero/1

# Listar todos los géneros ANDA
GET http://localhost:3000/genero/listar-generos

# Modificar un género por ID ANDA
PUT http://localhost:3000/genero/modificar-genero/13
Content-Type: application/json

{
    "genero": "western-occidental"
}

# Borrar un género por ID ANDA
DELETE http://localhost:3000/genero/borrar-genero/1

### POSTER

# Listar todos los posters
GET http://localhost:3000/poster/listar-poster
Accept: application/json

# Obtener un poster por ID
GET http://localhost:3000/poster/poster/1
Accept: application/json

# Agregar un nuevo poster
POST http://localhost:3000/poster/agregar-poster
Content-Type: application/json

{
    "image": "./posters/3.jpg",
    "contenido_id": 12,
}

# Modificar un poster existente
PUT http://localhost:3000/poster/modificar-poster/1
Content-Type: application/json

{
    "image": "./posters/6.jpg",
    "contenido_id": 12,
}

# Borrar un poster por ID
DELETE http://localhost:3000/poster/borrar-poster/1
Accept: application/json

### ACTOR_CONTENIDO
# Traer todas las películas de un actor
GET http://localhost:3000/actor_contenido/actor/:actorId/contenidos

# Traer todos los actores de una pelicula
GET http://localhost:3000/actor_contenido//contenido/:contenidoId/actores

#Asociar un contenido a un actor
POST 



